web:
  host: 0.0.0.0
  port: 8080
  ssl:
    cert: null
    key: null

logger:
  path: .logs

streams:
  - name: Garage Front Cam
    sorce: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4
    timeout: 15
